[workspace]
members = ["workspace/apps/staking/contracts", "workspace/packages/contracts"]


[workspace.dependencies]
starknet = "2.8.0"
assert_macros = "2.8.0"
openzeppelin = "0.15.1"
snforge_std = "0.30.0"

[scripts]
test = "snforge test"

[dev-cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"