[workspace]
members = ["workspace/apps/staking/contracts", "workspace/packages/contracts"]


[workspace.dependencies]
starknet = "2.8.0"
openzeppelin = "0.15.1"
snforge_std = "0.27.0"

[scripts]
test = "snforge test"
